name: Python Package using Conda

on: [push]

defaults:
  run:
    shell: bash -el {0}

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_list: Crate,crate,fo,tre

  formatting:
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: write # for marocchino/sticky-pull-request-comment to create or update PR comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: black
          create-args: black
          cache-environment: false

      - name: Check formatting
        run: black --check --diff cobra.py tests.py

  testing:
    runs-on: ubuntu-latest
    needs: formatting

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: cobra
          create-args: blast python pytest biopython pysam pandas
          cache-environment: true
          condarc: |
            channels:
              - conda-forge
              - bioconda
              - defaults
          init-shell: bash

      - name: Test local
        env:
          CI: true
        run: |
          for i in {1..5}; do
            pytest tests.py
          done
